import { describe, expect, it } from 'vitest';
import { createReportContextFromData } from '@allurereport/ci/report-context';
import { renderReportSummaryMarkdown } from '@allurereport/ci/report-markdown';
import { renderPrComment } from '../../src/renderer/markdown.js';

function createContext(remoteHref?: string) {
  return createReportContextFromData({
    summaries: [
      {
        name: 'Awesome',
        plugin: 'awesome',
        status: 'failed',
        duration: 1500,
        stats: { total: 3, passed: 2, failed: 1, broken: 0, skipped: 0, unknown: 0 },
        remoteHref,
      },
    ],
  });
}

const marker = '<!-- custom-report-marker -->';
const footer =
  '<sub>Generated by <a href="https://github.com/quokkify/allure-report-action">quokkify/allure-report-action</a> · <a href="https://github.com/quokkify/allure-report-action/releases/latest">v1.2.3</a></sub>';

describe('PR comment extensions', () => {
  it('keeps the complete official summary unchanged and appends ownership metadata', () => {
    const context = createContext('https://example.com/report?run=42');
    const body = renderPrComment({
      context,
      forkPr: false,
      actionVersion: '1.2.3',
      commentMarker: marker,
    });

    expect(context.totals.stats).toMatchObject({ total: 3, passed: 2, failed: 1 });
    expect(body).toBe(
      [renderReportSummaryMarkdown(context).trimEnd(), footer, marker].join('\n\n')
    );
    expect(body).toContain('# Allure Report Summary');
    expect(body).toContain('passed=2&failed=1');
    expect(body).toContain('<a href="https://example.com/report?run=42">awesome</a>');
    expect(body).not.toContain('Tests by layer');
  });

  it('adds a missing-link note after the official summary', () => {
    const context = createContext();
    const body = renderPrComment({
      context,
      forkPr: false,
      actionVersion: '1.2.3',
      commentMarker: marker,
    });
    expect(body).toBe(
      [
        renderReportSummaryMarkdown(context).trimEnd(),
        '_GitHub Pages URL not available for this run._',
        footer,
        marker,
      ].join('\n\n')
    );
  });

  it('adds the fork notice without the missing-link notice', () => {
    const context = createContext();
    const body = renderPrComment({
      context,
      forkPr: true,
      actionVersion: '1.2.3',
      commentMarker: marker,
    });
    expect(body).toContain('_GitHub Pages previews are disabled for fork pull requests._');
    expect(body).not.toContain('URL not available');
    expect(body.endsWith(marker)).toBe(true);
  });

  it.each([
    ['1.2.3', 'v1.2.3'],
    ['v1.2.3', 'v1.2.3'],
    [' 1.2.3 ', 'v1.2.3'],
    ['', 'unversioned'],
  ])('formats action version %j as %s', (actionVersion, expected) => {
    const body = renderPrComment({
      context: createContext(),
      forkPr: false,
      actionVersion,
      commentMarker: marker,
    });
    expect(body).toContain(`>${expected}</a></sub>`);
  });
});
