/**
 * Tests for Markdown renderer
 */
import { describe, it, expect } from 'vitest';
import { renderPrComment } from '../../src/renderer/markdown.js';
import { AggregatedResults, TestSummary, emptyStats } from '../../src/report/model.js';
describe('Markdown Renderer', () => {
  const createMockAggregated = (overrides: Partial<AggregatedResults> = {}): AggregatedResults => {
    const base: AggregatedResults = {
      byEpic: {
        unit: { ...emptyStats(), total: 10, passed: 10 },
        api: { ...emptyStats(), total: 5, passed: 5 },
        ui: { ...emptyStats(), total: 3, passed: 3 },
        'end-to-end': { ...emptyStats(), total: 2, passed: 2 },
        other: { ...emptyStats(), total: 1, passed: 1 },
      },
      total: { ...emptyStats(), total: 21, passed: 21 },
      resultCount: 21,
      layers: [
        {
          id: 'unit',
          label: 'Unit (base)',
          epics: ['unit'],
          stats: { ...emptyStats(), total: 10, passed: 10 },
        },
        {
          id: 'api',
          label: 'Integration (middle)',
          epics: ['api'],
          stats: { ...emptyStats(), total: 5, passed: 5 },
        },
        {
          id: 'ui_e2e',
          label: 'UI / E2E (top)',
          epics: ['ui', 'end-to-end'],
          stats: { ...emptyStats(), total: 5, passed: 5 },
        },
      ],
      otherEpicTotal: 1,
      pyramidTotal: 21,
      unitShare: 10 / 21,
      apiShare: 5 / 21,
      e2eShare: 5 / 21,
    };
    return { ...base, ...overrides };
  };

  const createMockSummary = (overrides: Partial<TestSummary> = {}): TestSummary => ({
    total: 21,
    passed: 20,
    failed: 1,
    broken: 0,
    skipped: 0,
    unknown: 0,
    ...overrides,
  });

  it('renders passing report with all sections', () => {
    const markdown = renderPrComment({
      summary: createMockSummary({ passed: 21, failed: 0 }),
      aggregated: createMockAggregated(),
      pagesUrl: 'https://example.com/report',
      forkPr: false,
      sourceRunId: '12345',
      actionVersion: '0.1.0',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain('## ✅ Allure Report — passed');
    expect(markdown).toContain('21 / 21 tests passed');
    expect(markdown).toContain('100% pass rate');
    expect(markdown).not.toContain('failed');
    expect(markdown).toContain('[View report ↗](https://example.com/report?run=12345)');
    expect(markdown).toContain('<details>');
    expect(markdown).toContain('Tests by layer');
    expect(markdown).toContain('| Unit | 10 | 10 | 0 | 0 | 0 |');
    expect(markdown).toContain('| Integration | 5 | 5 | 0 | 0 | 0 |');
    expect(markdown).toContain('Generated by');
    expect(markdown).toContain('quokkify/allure-report-action');
    expect(markdown).toContain('v0.1.0');
    expect(markdown).toContain('<!-- test-marker -->');
    expect(markdown.endsWith('<!-- test-marker -->')).toBe(true);
  });

  it('renders failing report with red status', () => {
    const markdown = renderPrComment({
      summary: createMockSummary({ total: 10, passed: 5, failed: 5 }),
      aggregated: createMockAggregated({
        total: { ...emptyStats(), total: 10, passed: 5, failed: 5 },
      }),
      pagesUrl: 'https://example.com/report',
      forkPr: false,
      sourceRunId: '',
      actionVersion: '0.1.0',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain('## ❌ Allure Report — failures detected');
    expect(markdown).toContain('5 / 10 tests passed');
    expect(markdown).toContain('50% pass rate');
    expect(markdown).toContain('5 failed');
  });

  it('renders empty report with neutral status', () => {
    const markdown = renderPrComment({
      summary: createMockSummary({ total: 0, passed: 0, failed: 0 }),
      aggregated: createMockAggregated({ total: { ...emptyStats(), total: 0 } }),
      pagesUrl: '',
      forkPr: false,
      sourceRunId: '',
      actionVersion: '0.1.0',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain('## ⚪ Allure Report — no tests');
    expect(markdown).toContain('No tests found · no pass rate');
  });

  it('handles unknown results', () => {
    const markdown = renderPrComment({
      summary: createMockSummary({ total: 10, passed: 5, unknown: 2 }),
      aggregated: createMockAggregated({
        total: { ...emptyStats(), total: 10, passed: 5, unknown: 2 },
        byEpic: {
          unit: emptyStats(),
          api: emptyStats(),
          ui: emptyStats(),
          'end-to-end': emptyStats(),
          other: { ...emptyStats(), total: 2, unknown: 2 },
        },
      }),
      pagesUrl: 'https://example.com/report',
      forkPr: false,
      sourceRunId: '',
      actionVersion: '0.1.0',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain('2 unknown');
    expect(markdown).toContain('| Unknown |');
  });

  it('handles fork PR without pages link', () => {
    const markdown = renderPrComment({
      summary: createMockSummary(),
      aggregated: createMockAggregated(),
      pagesUrl: 'https://example.com/report',
      forkPr: true,
      sourceRunId: '',
      actionVersion: '0.1.0',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain(
      'Preview on GitHub Pages is only published for PRs from the same repository'
    );
  });

  it('handles missing pages URL', () => {
    const markdown = renderPrComment({
      summary: createMockSummary(),
      aggregated: createMockAggregated(),
      pagesUrl: '',
      forkPr: false,
      sourceRunId: '',
      actionVersion: '0.1.0',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain('GitHub Pages URL not available for this run');
    expect(markdown).not.toContain('[View report ↗]');
  });

  it('formats version correctly', () => {
    const markdown = renderPrComment({
      summary: createMockSummary(),
      aggregated: createMockAggregated(),
      pagesUrl: '',
      forkPr: false,
      sourceRunId: '',
      actionVersion: '1.2.3',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain('v1.2.3');
  });

  it('adds v prefix to version without it', () => {
    const markdown = renderPrComment({
      summary: createMockSummary(),
      aggregated: createMockAggregated(),
      pagesUrl: '',
      forkPr: false,
      sourceRunId: '',
      actionVersion: '0.1.0',
      commentMarker: '<!-- test-marker -->',
    });

    expect(markdown).toContain('v0.1.0');
  });
});
