#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d "${RUNNER_TEMP:-/tmp}/allure-report-action-smoke-XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP/results" "$TMP/source-results/module-a/allure-results" "$TMP/source-results/module-b/allure-results"

python3 - "$TMP/results" "$TMP/source-results/module-a/allure-results" "$TMP/source-results/module-b/allure-results" <<'PY'
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
module_a_source = pathlib.Path(sys.argv[2])
module_b_source = pathlib.Path(sys.argv[3])

documents = [
    {
        "uuid": "unit-1",
        "name": "labeled unit",
        "status": "passed",
        "stage": "finished",
        "start": 1,
        "stop": 2,
        "labels": [
            {"name": "epic", "value": "unit"},
            {"name": "module", "value": "module-a"},
        ],
    },
    {
        "uuid": "plain-1",
        "name": "without epic metadata",
        "status": "passed",
        "stage": "finished",
        "start": 1,
        "stop": 2,
        "labels": [],
    },
    {
        "uuid": "playwright-1",
        "name": "playwright without epic metadata",
        "status": "passed",
        "stage": "finished",
        "start": 1,
        "stop": 2,
        "labels": [
            {"name": "framework", "value": "playwright"},
            {"name": "module", "value": "module-b"},
        ],
    },
]
for document in documents:
    destination = module_a_source if document["uuid"] == "unit-1" else module_b_source
    (destination / f"{document['uuid']}-result.json").write_text(json.dumps(document))

(module_a_source / "ci-env-fragment.properties").write_text(
    "Module A.Module=module-a\nModule A.Runner=runner-a\n"
)
(module_b_source / "ci-env-fragment.properties").write_text(
    "Module B.Module=module-b\nModule B.Runner=runner-b\n"
)
(root / "stale-result.json").write_text(json.dumps({"uuid": "stale"}))
(root / "environment.properties").write_text("GitHub.RunId=123\n")
PY

(
  cd "$TMP"
  node "$ROOT/dist/cli.cjs" prepare-results \
    --source-root source-results \
    --results results \
    --module-label module \
    --auto false
  node "$ROOT/dist/cli.cjs" module-config \
    --results results \
    --config "$ROOT/tests/allurerc.mjs" \
    --output effective-allurerc.mjs \
    --module-label module
  npx --yes allure@3.14.2 generate results -o report --config effective-allurerc.mjs
  node "$ROOT/dist/cli.cjs" badges --results results --out report
  node "$ROOT/dist/cli.cjs" pr-body \
    --results results \
    --report report \
    --output comment.md \
    --pages-url "https://example.invalid/report" \
    --fork-pr false \
    --source-run-id 123 \
    --action-version 0.1.3 \
    --comment-marker '<!-- allure-report-action-smoke -->'
  PYRAMID_SOURCE_RUN_ID=123 PYRAMID_HEAD_SHA=0123456789abcdef \
    node "$ROOT/dist/cli.cjs" pyramid \
      --results results \
      --output pyramid.md \
      --json pyramid.json
  node "$ROOT/dist/cli.cjs" pyramid-check \
    --results results \
    --json pyramid-gates.json
)

python3 - "$TMP" <<'PY'
import json
import pathlib
import sys

root = pathlib.Path(sys.argv[1])
body = (root / "comment.md").read_text()
pyramid = (root / "pyramid.md").read_text()

assert "## ✅ Allure Report — passed" in body
assert "3 / 3 tests passed · 100% pass rate" in body
assert "| E2E | 1 | 1 | 0 | 0 | 0 |" in body
assert "| No epic assigned | 1 | 1 | 0 | 0 | 0 |" in body
assert '<sub>Generated by <a href="https://github.com/quokkify/allure-report-action">quokkify/allure-report-action</a> · <a href="https://github.com/quokkify/allure-report-action/releases/latest">v0.1.3</a></sub>' in body
assert body.endswith("<!-- allure-report-action-smoke -->")
assert "Canonical policy:" not in pyramid
assert (root / "report/index.html").is_file()

gates = json.loads((root / "pyramid-gates.json").read_text())
assert gates["metrics"]["otherEpicTotal"] == 1

import json as _json
environments = _json.loads((root / "report/widgets/environments.json").read_text())
assert environments == [
    {"id": "default", "name": "default"},
    {"id": "module-a", "name": "module-a"},
    {"id": "module-b", "name": "module-b"},
]

default_variables = _json.loads((root / "report/widgets/default/variables.json").read_text())
module_a_variables = _json.loads((root / "report/widgets/module-a/variables.json").read_text())
module_b_variables = _json.loads((root / "report/widgets/module-b/variables.json").read_text())

assert default_variables == {"GitHub.RunId": "123"}
assert module_a_variables == {
    "GitHub.RunId": "123",
    "Runner": "runner-a",
    "Module": "module-a",
}
assert module_b_variables == {
    "GitHub.RunId": "123",
    "Runner": "runner-b",
    "Module": "module-b",
}

print("smoke: report, module-scoped environments/variables, missing Epic fallbacks, and pyramid outputs OK")
PY

echo "smoke test passed!"