/**
 * Tests for commands
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { runBadges } from '../../src/commands/badges.js';
import { runPrBody } from '../../src/commands/pr-body.js';
import { runPyramid } from '../../src/commands/pyramid.js';
import { runPyramidCheck } from '../../src/commands/pyramid-check.js';

describe('Commands', () => {
  let tempDir: string;
  let resultsDir: string;
  let reportDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'command-test-'));
    resultsDir = path.join(tempDir, 'results');
    reportDir = path.join(tempDir, 'report');
    fs.mkdirSync(resultsDir, { recursive: true });
    fs.mkdirSync(path.join(reportDir, 'widgets'), { recursive: true });
    fs.mkdirSync(path.join(reportDir, 'badges'), { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  const writeResult = (name: string, data: object) => {
    fs.writeFileSync(path.join(resultsDir, `${name}-result.json`), JSON.stringify(data));
  };

  describe('runBadges', () => {
    it('generates badge files', () => {
      writeResult('unit1', {
        uuid: '1',
        status: 'passed',
        labels: [{ name: 'epic', value: 'unit' }],
      });
      writeResult('api1', {
        uuid: '2',
        status: 'failed',
        labels: [{ name: 'epic', value: 'api' }],
      });

      runBadges({ resultsDir, reportDir });

      const totalBadge = JSON.parse(
        fs.readFileSync(path.join(reportDir, 'badges', 'total.json'), 'utf8')
      );
      expect(totalBadge.label).toBe('all tests');
      expect(totalBadge.color).toBe('red'); // has failed

      const unitBadge = JSON.parse(
        fs.readFileSync(path.join(reportDir, 'badges', 'unit.json'), 'utf8')
      );
      expect(unitBadge.label).toBe('unit tests');
      expect(unitBadge.color).toBe('brightgreen');

      const apiBadge = JSON.parse(
        fs.readFileSync(path.join(reportDir, 'badges', 'api.json'), 'utf8')
      );
      expect(apiBadge.color).toBe('red');
    });
  });

  describe('runPrBody', () => {
    beforeEach(() => {
      // Write widget summary
      fs.writeFileSync(
        path.join(reportDir, 'widgets', 'summary.json'),
        JSON.stringify({
          statistic: { total: 3, passed: 2, failed: 1, broken: 0, skipped: 0, unknown: 0 },
        })
      );
    });

    it('generates PR comment markdown', () => {
      writeResult('unit1', {
        uuid: '1',
        status: 'passed',
        labels: [{ name: 'epic', value: 'unit' }],
      });
      writeResult('api1', {
        uuid: '2',
        status: 'failed',
        labels: [{ name: 'epic', value: 'api' }],
      });
      writeResult('plain', { uuid: '3', status: 'passed' });

      const outputFile = path.join(tempDir, 'comment.md');
      runPrBody({
        resultsDir,
        reportDir,
        outputFile,
        pagesUrl: 'https://example.com/report',
        forkPr: false,
        sourceRunId: '123',
        actionVersion: '0.1.0',
        commentMarker: '<!-- marker -->',
      });

      const content = fs.readFileSync(outputFile, 'utf8');
      expect(content).toContain('## ❌ Allure Report — failures detected');
      expect(content).toContain('2 / 3 tests passed');
      expect(content).toContain('1 failed');
      expect(content).toContain('[View report ↗](https://example.com/report?run=123)');
      expect(content).toContain('Generated by');
      expect(content).toContain('v0.1.0');
      expect(content.endsWith('<!-- marker -->')).toBe(true);
    });
  });

  describe('runPyramid', () => {
    it('generates pyramid markdown and JSON', () => {
      writeResult('unit1', {
        uuid: '1',
        status: 'passed',
        labels: [{ name: 'epic', value: 'unit' }],
      });
      writeResult('unit2', {
        uuid: '2',
        status: 'passed',
        labels: [{ name: 'epic', value: 'unit' }],
      });
      writeResult('api1', {
        uuid: '3',
        status: 'passed',
        labels: [{ name: 'epic', value: 'api' }],
      });
      writeResult('e2e1', {
        uuid: '4',
        status: 'passed',
        labels: [{ name: 'epic', value: 'end-to-end' }],
      });
      writeResult('plain', { uuid: '5', status: 'passed' });

      const outputMd = path.join(tempDir, 'pyramid.md');
      const outputJson = path.join(tempDir, 'pyramid.json');

      runPyramid({
        resultsDir,
        outputMd,
        outputJson,
        policyPath: 'docs/testing/test-pyramid.md',
        sourceRunId: '12345',
        headSha: 'abcdef123456',
      });

      expect(fs.existsSync(outputMd)).toBe(true);
      expect(fs.existsSync(outputJson)).toBe(true);

      const md = fs.readFileSync(outputMd, 'utf8');
      expect(md).toContain('# Test pyramid snapshot');
      expect(md).toContain('Source workflow run id: `12345`');
      expect(md).toContain('Head SHA: `abcdef1`');
      expect(md).toContain('| Unit (base) | `unit` | **2** |');
      expect(md).toContain('| Integration (middle) | `api` / `integration` | **1** |');
      expect(md).toContain('| UI / E2E (top) | `end-to-end` / `ui` | **1** |');

      const json = JSON.parse(fs.readFileSync(outputJson, 'utf8'));
      expect(json.schemaVersion).toBe(1);
      expect(json.pyramidLayerTotals).toEqual({ unit: 2, api: 1, ui_e2e: 1 });
      expect(json.pyramidTotal).toBe(4);
    });
  });

  describe('runPyramidCheck', () => {
    it('writes quality gates JSON and emits warnings', () => {
      writeResult('unit1', {
        uuid: '1',
        status: 'passed',
        labels: [{ name: 'epic', value: 'unit' }],
      });
      writeResult('e2e1', {
        uuid: '2',
        status: 'passed',
        labels: [{ name: 'epic', value: 'end-to-end' }],
      });
      writeResult('e2e2', {
        uuid: '3',
        status: 'passed',
        labels: [{ name: 'epic', value: 'end-to-end' }],
      });
      writeResult('e2e3', {
        uuid: '4',
        status: 'passed',
        labels: [{ name: 'epic', value: 'end-to-end' }],
      });
      // High E2E share should trigger warning

      const outputJson = path.join(tempDir, 'gates.json');

      // Capture console output
      const consoleSpy = vi.spyOn(console, 'log').mockImplementation(() => {});

      runPyramidCheck({ resultsDir, outputJson });

      consoleSpy.mockRestore();

      expect(fs.existsSync(outputJson)).toBe(true);

      const json = JSON.parse(fs.readFileSync(outputJson, 'utf8'));
      expect(json.schemaVersion).toBe(1);
      expect(json.advisoryOnly).toBe(true);
      expect(json.exitCodePolicy).toBe('always_zero');
      expect(json.gates.warnings.length).toBeGreaterThan(0);
      expect(json.metrics.e2eShare).toBeGreaterThan(0.28);
    });
  });
});
