import type { ReportContext } from '@allurereport/ci/report-context';
import { renderReportSummaryMarkdown } from '@allurereport/ci/report-markdown';

import { ACTION_REPOSITORY_URL } from '../report/model.js';

export interface PrCommentData {
  context: ReportContext;
  forkPr: boolean;
  actionVersion: string;
  commentMarker: string;
}

export function renderPrComment(data: PrCommentData): string {
  const { context, forkPr, actionVersion, commentMarker } = data;
  const sections = [renderReportSummaryMarkdown(context).trimEnd()];
  if (forkPr) {
    sections.push('_GitHub Pages previews are disabled for fork pull requests._');
  } else if (!context.reports.some(report => report.remoteHref)) {
    sections.push('_GitHub Pages URL not available for this run._');
  }
  const version = actionVersion.trim();
  const displayVersion = version
    ? version.startsWith('v')
      ? version
      : `v${version}`
    : 'unversioned';
  sections.push(
    `<sub>Generated by <a href="${ACTION_REPOSITORY_URL}">quokkify/allure-report-action</a> · <a href="${ACTION_REPOSITORY_URL}/releases/latest">${displayVersion}</a></sub>`,
    commentMarker
  );
  return sections.join('\n\n');
}
